#!/bin/sh
/Users/jondotsoy/.nvm/versions/node/v20.4.0/bin/node /Users/jondotsoy/Repositories/jondotsoy/nutbot-sdk/src/anchor.demon.js >> /Users/jondotsoy/.logs/nutbot_anchor.log 2>> /Users/jondotsoy/.logs/nutbot_anchor.err
